config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats do
    collection do
      get 'search', to: 'flats#search'
    end
  end

  root 'flats#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: [:show, :destroy, :edit, :update]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(val_params)
    if @flat.save
      redirect_to flats_path, notice: "Successfully created!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @flat.update(val_params)
    if @flat.save
      redirect_to flat_path(@flat), notice: "Successfully updated!"
    else
      render :new
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path(@flat), notice: "Successfully deleted!"
  end

  def search
    @keyword = params[:query]
    @flats = Flat.where("name LIKE '%#{@keyword}%'")
    redirect_to flats_path, notice: "You searched for #{@keyword}. No matched result found." if @flats.empty?
  end

  private

  def val_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def find_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<%= notice if notice %>

<div class="col-xs-12 col-sm-4 col-sm-offset-4">
  <div class="row">
    <%= simple_form_for(@flat) do |f| %>
      <% if @flat.errors.any? %>
        <div class="errors-container">
          <ul>
            <% @flat.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <h2>Edit a flat</h2>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :price_per_night %>
        <%= f.text_field :price_per_night, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :number_of_guests %>
        <%= f.text_field :number_of_guests, class: "form-control" %>
      </div>
      <%= f.button :submit, class: "btn btn-primary" %>
      <%= link_to "Reset input", "#", class: "btn btn-danger" %>
    <% end %>
  </div>
</div>

app/views/flats/index.html.erb
<% if notice %>
  <div class="alert alert-info">
    <button type="button" class="close" id="alertbtn">×</button>
    <p><%= notice %></p>
  </div>
<% end %>

<div class="container">

  <div class="row">
    <div class="col-12">
      <h1>All our Flats</h1>
    </div>
  </div>

  <div class="row">
    <% @flats.each do |f| %>
      <div class="col-4">
        <div class="flex-card">
          <div class="card-body">
            <h5 class="card-title"><%= f.name %></h5>
            <h6 class="card-subtitle text-muted"><%= f.address %></h6>
            <p class="card-text"><%= f.description %></p>
            <ul class="list-inline">
              <li class="inline-items">
                <i class="material-icons mr-2">people</i>
                <span><%= f.number_of_guests %></span>
              </li>
              <li class="inline-items">
                <i class="material-icons mr-2">attach_money</i>
                <span><%= f.number_of_guests %></span>
              </li>
            </ul>
            <%= link_to "More details", flat_path(f) %>
            <%= link_to "Edit", edit_flat_path(f) %>
            <%= link_to "Remove", flat_path(f), method: :delete, data: {confirm:"Are you sure?"} %>
          </div>
        </div>
      </div>
    <% end %>
  </div>


</div>

app/views/flats/new.html.erb
<%= notice if notice %>

<div class="col-xs-12 col-sm-4 col-sm-offset-4">
  <div class="row">
    <%= simple_form_for(@flat) do |f| %>
      <% if @flat.errors.any? %>
        <div class="errors-container">
          <ul>
            <% @flat.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <h2>Add a new flat</h2>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :price_per_night %>
        <%= f.text_field :price_per_night, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :number_of_guests %>
        <%= f.text_field :number_of_guests, class: "form-control" %>
      </div>
      <%= f.button :submit, class: "btn btn-primary" %>
      <%= link_to "Clear input", "#", class: "btn btn-danger" %>
    <% end %>
  </div>
</div>

app/views/flats/search.html.erb
<div class="container">

  <div class="row">
    <div class="col-12">
      <h1>Results</h1>
      <p>You searched for <strong><%= @keyword %></strong>. We found <%= @flats.count %> out of our <%= Flat.count %> flats on our website.</p>
    </div>
  </div>

  <div class="row">
    <% @flats.each do |f| %>
      <div class="col-4">
        <div class="flex-card">
          <div class="card-body">
            <h5 class="card-title"><%= f.name %></h5>
            <h6 class="card-subtitle text-muted"><%= f.address %></h6>
            <p class="card-text"><%= f.description %></p>
            <ul class="list-inline">
              <li class="inline-items">
                <i class="material-icons mr-2">people</i>
                <span><%= f.number_of_guests %></span>
              </li>
              <li class="inline-items">
                <i class="material-icons mr-2">attach_money</i>
                <span><%= f.number_of_guests %></span>
              </li>
            </ul>
            <%= link_to "More details", flat_path(f) %>
            <%= link_to "Edit", edit_flat_path(f) %>
            <%= link_to "Remove", flat_path(f), method: :delete, data: {confirm:"Are you sure?"} %>
          </div>
        </div>
      </div>
    <% end %>
  </div>


</div>

app/views/flats/show.html.erb
<%= notice %>

<div class="row" style="display:flex; justify-content: center;">
  <div class="col-xs-12 col-sm-4 text-center">
    <h1><%= @flat.name %></h1>
    <ul class="list-group">
      <li class="list-group-item">
        Address : <%= @flat.address %>
      </li>
      <li class="list-group-item">
        Description : <%= @flat.description %>
      </li>
      <li class="list-group-item">
        Price : <%= @flat.price_per_night %>
      </li>
      <li class="list-group-item">
       Numer of People : <%= @flat.number_of_guests %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar-wagon">
      <a class="navbar-brand" href="/">Simple Airbnb</a>
      <div class="navbar-wagon-right">
        <form class="form-inline my-2 my-lg-0" action="/flats/search">
          <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value="">
          <button class="btn navbar-wagon-link" type="submit">Search</button>
        </form>
        <a class="btn navbar-wagon-link" href="/flats/new">Add Flat</a>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>